DROP TABLE IF EXISTS recording_sessions CASCADE;
DROP TABLE IF EXISTS compositions CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS producers CASCADE;
DROP TABLE IF EXISTS employees CASCADE;